In [151]:
import numpy as np
import pandas as pd

data = pd.read_csv("../data/student_merged.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  freetime goout  Dalc  Walc  health absences  G1  G2  G3 matiere  
0        3     4     1     1       3        6   5   6   6   Maths  
1        3     3     1     1       3        4   5   5   6   Maths  
2        3     2     2     3       3       10   7   8  10   Maths  
3        2     2     1     1       5        2  15  14  15   Maths  
4        3     2     1     2       5        4   6  10  10   Maths  

[5 rows x 34 columns]

# Nettoyage et Manipulation des données

Tout d'abord, on renomme les colonnes pour les rendre plus explicites

In [152]:
data.rename(columns={
        'famsize':'taille_famille',
        'Pstatus':'parents_cohabitation',
        'Medu':'niveau_edu_mere',
        'Fedu':'niveau_edu_pere',
        'Mjob':'emploi_mere',
        'Fjob':'emploi_pere',
        'reason':'raison_choix_ecole',
        'guardian':'tuteur',
        'schoolsup':'soutien_edu_sup',
        'famsup':'soutien_fam_sup',
        'paid':'cours_payant_sup',
        'nursery':'frequente_maternelle',
        'higher':'etu_superieur',
        'famrel':'qualite_relation_fam',
        'goout':'sorties_amis',
        'Dalc':'conso_alcool_workday',
        'Walc':'conso_alcool_weekend',
    },
    inplace=True
)

In [153]:
data.head()

school sex  age address taille_famille parents_cohabitation  \
0     GP   F   18       U            GT3                    A   
1     GP   F   17       U            GT3                    T   
2     GP   F   15       U            LE3                    T   
3     GP   F   15       U            GT3                    T   
4     GP   F   16       U            GT3                    T   

   niveau_edu_mere  niveau_edu_pere emploi_mere emploi_pere  ... freetime  \
0                4                4     at_home     teacher  ...        3   
1                1                1     at_home       other  ...        3   
2                1                1     at_home       other  ...        3   
3                4                2      health    services  ...        2   
4                3                3       other       other  ...        3   

  sorties_amis  conso_alcool_workday  conso_alcool_weekend  health absences  \
0            4                     1                     1       3        6   
1            3                     1                     1       3        4   
2            2                     2                     3       3       10   
3            2                     1                     1       5        2   
4            2                     1                     2       5        4   

   G1  G2  G3 matiere  
0   5   6   6   Maths  
1   5   5   6   Maths  
2   7   8  10   Maths  
3  15  14  15   Maths  
4   6  10  10   Maths  

[5 rows x 34 columns]

### Vérifions et corrigeons pour chaque colonne les différentes erreurs lexicales, de formatage ou d'irrégularité, ainsi que les outliers.

In [154]:
data.loc[~data["school"].isin(["GP", "MS"]), ]

Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

Colonne ```school``` ok ✅

In [155]:
data.loc[~data["sex"].isin(["M", "F"]), ]

Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

Colonne ```sex``` ok ✅

In [156]:
data['age'].describe()

count    1044.000000
mean       16.726054
std         1.239975
min        15.000000
25%        16.000000
50%        17.000000
75%        18.000000
max        22.000000
Name: age, dtype: float64

Colonne ```age``` ok ✅

In [157]:
data.loc[~data["address"].isin(["U", "R"]), ]


Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

Colonne ```address``` ok ✅

In [158]:
data.loc[~data["taille_famille"].isin(["LE3", "GT3"]), ]

Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

Colonne ```taille_famille``` ok ✅

In [159]:
data.loc[~data["parents_cohabitation"].isin(["A", "T"]), ]

Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

Pour cette colonne, on modifiera les valeurs "A" par False et "T" par True pour signifier plus explicitement si les parents habitent ensemble ou pas.

In [160]:
data.loc[data["parents_cohabitation"] == "A", "parents_cohabitation"] = False
data.loc[data["parents_cohabitation"] == "T", "parents_cohabitation"] = True

In [161]:
data['parents_cohabitation'].head()

0    False
1     True
2     True
3     True
4     True
Name: parents_cohabitation, dtype: object

Colonne ```parents_cohabitation``` ok ✅

In [162]:
for x in ["niveau_edu_mere", "niveau_edu_pere"]:
    errors = data.loc[~data[x].isin([0, 1, 2, 3, 4]), ]
errors

Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

Pour cette colonne, on modifiera les valeurs numériques par les valeurs nominales correspondantes pour signifier plus explicitement leur niveau d'étude.

In [163]:
for x in ["niveau_edu_mere", "niveau_edu_pere"]:
    data.loc[data[x] == 0, x] = "aucun"
    data.loc[data[x] == 1, x] = "primaire"
    data.loc[data[x] == 2, x] = "college"
    data.loc[data[x] == 3, x] = "lycee"
    data.loc[data[x] == 4, x] = "universite"
data[["niveau_edu_pere", "niveau_edu_mere"]].head()

/tmp/ipykernel_10829/3742040696.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'aucun' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data[x] == 0, x] = "aucun"
/tmp/ipykernel_10829/3742040696.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'aucun' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  data.loc[data[x] == 0, x] = "aucun"


niveau_edu_pere niveau_edu_mere
0      universite      universite
1        primaire        primaire
2        primaire        primaire
3         college      universite
4           lycee           lycee

Colonnes ```niveau_edu_pere``` et ```niveau_edu_mere``` ok ✅

In [164]:
for x in ["emploi_mere", "emploi_pere", "raison_choix_ecole", "tuteur"]:
    print("-"*50)
    print("Variable: ", x)
    print(data[x].unique())

--------------------------------------------------
Variable:  emploi_mere
['at_home' 'health' 'other' 'services' 'teacher']
--------------------------------------------------
Variable:  emploi_pere
['teacher' 'other' 'services' 'health' 'at_home']
--------------------------------------------------
Variable:  raison_choix_ecole
['course' 'other' 'home' 'reputation']
--------------------------------------------------
Variable:  tuteur
['mother' 'father' 'other']


Colonnes ```emploi_mere```, ```emploi_pere```, ```raison_choix_ecole```, ```tuteur``` ok ✅

In [165]:
for x in ["traveltime", "studytime"]:
    errors = data.loc[~data[x].isin([1, 2, 3, 4]), ]
errors

Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

Colonnes ```traveltime```, ```studytime``` ok ✅

In [166]:
for x in ["failures", "qualite_relation_fam", "freetime", "sorties_amis", "conso_alcool_workday", "conso_alcool_weekend", "health", "absences"]:
    print("-"*50)
    print("Variable: ", x)
    print(data[x].unique())

--------------------------------------------------
Variable:  failures
[0 3 2 1]
--------------------------------------------------
Variable:  qualite_relation_fam
[4 5 3 1 2]
--------------------------------------------------
Variable:  freetime
[3 2 4 1 5]
--------------------------------------------------
Variable:  sorties_amis
[4 3 2 1 5]
--------------------------------------------------
Variable:  conso_alcool_workday
[1 2 5 3 4]
--------------------------------------------------
Variable:  conso_alcool_weekend
[1 3 2 4 5]
--------------------------------------------------
Variable:  health
[3 5 1 2 4]
--------------------------------------------------
Variable:  absences
[ 6  4 10  2  0 16 14  7  8 25 12 54 18 26 20 56 24 28  5 13 15 22  3 21
  1 75 30 19  9 11 38 40 23 17 32]


Colonnes ```failures```, ```qualite_relation_fam```, ```freetime```, ```sorties_amis```, ```conso_alcool_workday```, ```conso_alcool_weekend```, ```health```, ```absences``` ok ✅

In [167]:
for x in ["soutien_edu_sup", "soutien_fam_sup", "cours_payant_sup", "activities", "frequente_maternelle", "etu_superieur", "internet", "romantic"]:
    errors = data.loc[~data[x].isin(["yes", "no"]), ]
errors

Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

On initialise les valeurs "yes" à True et "no" à False.

In [168]:
for x in ["soutien_edu_sup", "soutien_fam_sup", "cours_payant_sup", "activities", "frequente_maternelle", "etu_superieur", "internet", "romantic"]:
    data.loc[data[x] == "yes", x] = True
    data.loc[data[x] == "no", x] = False

data[["soutien_edu_sup", "soutien_fam_sup", "cours_payant_sup", "activities", "frequente_maternelle", "etu_superieur", "internet", "romantic"]].head()

soutien_edu_sup soutien_fam_sup cours_payant_sup activities  \
0            True           False            False      False   
1           False            True            False      False   
2            True           False             True      False   
3           False            True             True       True   
4           False            True             True      False   

  frequente_maternelle etu_superieur internet romantic  
0                 True          True    False    False  
1                False          True     True    False  
2                 True          True     True    False  
3                 True          True     True     True  
4                 True          True    False    False

Colonnes "```soutien_edu_sup```", "```soutien_fam_sup```", "```cours_payant_sup```", "```activities```", "```frequente_maternelle```", "```etu_superieur```", "```internet```", "```romantic```" ok ✅

In [169]:
for x in ["G1", "G2", "G3"]:
    print("-"*50)
    print("Variable: ", x)
    print(data[x].describe())

--------------------------------------------------
Variable:  G1
count    1044.000000
mean       11.213602
std         2.983394
min         0.000000
25%         9.000000
50%        11.000000
75%        13.000000
max        19.000000
Name: G1, dtype: float64
--------------------------------------------------
Variable:  G2
count    1044.000000
mean       11.246169
std         3.285071
min         0.000000
25%         9.000000
50%        11.000000
75%        13.000000
max        19.000000
Name: G2, dtype: float64
--------------------------------------------------
Variable:  G3
count    1044.000000
mean       11.341954
std         3.864796
min         0.000000
25%        10.000000
50%        11.000000
75%        14.000000
max        20.000000
Name: G3, dtype: float64


Colonnes ```G1```, ```G2```, ```G3``` ok ✅

### Toutes les colonnes sont ✅. À présent, on vérifie les valeurs manquantes et les doublons

In [170]:
data.isnull().sum()

school                  0
sex                     0
age                     0
address                 0
taille_famille          0
parents_cohabitation    0
niveau_edu_mere         0
niveau_edu_pere         0
emploi_mere             0
emploi_pere             0
raison_choix_ecole      0
tuteur                  0
traveltime              0
studytime               0
failures                0
soutien_edu_sup         0
soutien_fam_sup         0
cours_payant_sup        0
activities              0
frequente_maternelle    0
etu_superieur           0
internet                0
romantic                0
qualite_relation_fam    0
freetime                0
sorties_amis            0
conso_alcool_workday    0
conso_alcool_weekend    0
health                  0
absences                0
G1                      0
G2                      0
G3                      0
matiere                 0
dtype: int64

Aucune valeur manquante détectée

In [171]:
data.loc[data.duplicated(), ]

Empty DataFrame
Columns: [school, sex, age, address, taille_famille, parents_cohabitation, niveau_edu_mere, niveau_edu_pere, emploi_mere, emploi_pere, raison_choix_ecole, tuteur, traveltime, studytime, failures, soutien_edu_sup, soutien_fam_sup, cours_payant_sup, activities, frequente_maternelle, etu_superieur, internet, romantic, qualite_relation_fam, freetime, sorties_amis, conso_alcool_workday, conso_alcool_weekend, health, absences, G1, G2, G3, matiere]
Index: []

[0 rows x 34 columns]

Aucun doublon détecté

In [172]:
data.head()

school sex  age address taille_famille parents_cohabitation niveau_edu_mere  \
0     GP   F   18       U            GT3                False      universite   
1     GP   F   17       U            GT3                 True        primaire   
2     GP   F   15       U            LE3                 True        primaire   
3     GP   F   15       U            GT3                 True      universite   
4     GP   F   16       U            GT3                 True           lycee   

  niveau_edu_pere emploi_mere emploi_pere  ... freetime sorties_amis  \
0      universite     at_home     teacher  ...        3            4   
1        primaire     at_home       other  ...        3            3   
2        primaire     at_home       other  ...        3            2   
3         college      health    services  ...        2            2   
4           lycee       other       other  ...        3            2   

   conso_alcool_workday  conso_alcool_weekend  health absences  G1  G2  G3  \
0                     1                     1       3        6   5   6   6   
1                     1                     1       3        4   5   5   6   
2                     2                     3       3       10   7   8  10   
3                     1                     1       5        2  15  14  15   
4                     1                     2       5        4   6  10  10   

  matiere  
0   Maths  
1   Maths  
2   Maths  
3   Maths  
4   Maths  

[5 rows x 34 columns]

## Exportation des données nettoyées

In [173]:
data.to_csv("../data/data_cleaned.csv", index=False)